services:
  - type: web
    name: taskflow-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health/readiness
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: supabase,render
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_USERNAME
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: TASKFLOW_PROXY_SECRET
        sync: false
      - key: APP_MAX_TASKS_PER_USER
        value: 2000
