import { Task } from './types';

export const initialTasks: Task[] = [
  // OVERDUE (before June 9, 2026)
  {
    id: 't1',
    title: 'Write API documentation',
    description: 'Document all REST endpoints for the v2 API. Include request/response schemas and error codes.',
    dueDate: '2026-06-04T10:00:00',
    priority: 'HIGH',
    status: 'ACTIVE',
    category: 'WORK',
  },
  {
    id: 't2',
    title: 'Review pull requests',
    description: 'Review pending PRs from the team before the sprint ends.',
    dueDate: '2026-06-05T14:00:00',
    priority: 'MEDIUM',
    status: 'DONE',
    category: 'WORK',
  },
  {
    id: 't3',
    title: 'Pay utility bills',
    description: '',
    dueDate: '2026-06-06T09:00:00',
    priority: 'HIGH',
    status: 'ACTIVE',
    category: 'PERSONAL',
  },

  // TODAY (June 9, 2026)
  {
    id: 't4',
    title: 'Morning workout',
    description: 'Upper body day. 45 minutes at the gym.',
    dueDate: '2026-06-09T07:00:00',
    priority: 'LOW',
    status: 'DONE',
    category: 'HEALTH',
  },
  {
    id: 't5',
    title: 'Sprint planning meeting',
    description: 'Q3 sprint kickoff. Prepare backlog items in advance.',
    dueDate: '2026-06-09T10:30:00',
    priority: 'HIGH',
    status: 'ACTIVE',
    category: 'WORK',
  },
  {
    id: 't6',
    title: 'Buy groceries',
    description: 'Fruits, vegetables, coffee, and oat milk.',
    dueDate: '2026-06-09T18:00:00',
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'PERSONAL',
  },
  {
    id: 't7',
    title: 'Take vitamins',
    description: '',
    dueDate: '2026-06-09T08:00:00',
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'HEALTH',
  },

  // UPCOMING
  {
    id: 't8',
    title: 'Finalize Q3 budget report',
    description: 'Consolidate department spend data and present projections.',
    dueDate: '2026-06-12T09:00:00',
    priority: 'HIGH',
    status: 'ACTIVE',
    category: 'WORK',
  },
  {
    id: 't9',
    title: 'Doctor appointment',
    description: 'Annual checkup at City Medical Center.',
    dueDate: '2026-06-14T14:00:00',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    category: 'HEALTH',
  },
  {
    id: 't10',
    title: 'Team offsite dinner',
    description: 'Book a table at the Italian place downtown.',
    dueDate: '2026-06-15T19:00:00',
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'PERSONAL',
  },
  {
    id: 't11',
    title: 'Deploy new feature to production',
    description: 'Feature flag is ready. Coordinate with DevOps for zero-downtime deploy.',
    dueDate: '2026-06-18T10:00:00',
    priority: 'URGENT',
    status: 'ACTIVE',
    category: 'WORK',
  },
  {
    id: 't12',
    title: 'Weekly review',
    description: 'Reflect on the week and plan the next one.',
    dueDate: '2026-06-20T17:00:00',
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'PERSONAL',
  },
  {
    id: 't13',
    title: 'Fix Docker Compose config',
    description: '',
    dueDate: '2026-06-22T11:00:00',
    priority: 'MEDIUM',
    status: 'ACTIVE',
    category: 'WORK',
  },
  {
    id: 't14',
    title: '10k run training',
    description: 'Tempo run, 8km target pace.',
    dueDate: '2026-06-25T06:30:00',
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'HEALTH',
  },

  // SOMEDAY (no due date)
  {
    id: 't15',
    title: 'Learn Rust programming',
    description: 'Work through "The Rust Programming Language" book.',
    dueDate: null,
    priority: 'LOW',
    status: 'ACTIVE',
    category: 'PERSONAL',
  },
  {
    id: 't16',
    title: 'Refactor authentication module',
    description: 'Migrate from JWT-based to session-based auth for compliance.',
    dueDate: null,
    priority: 'MEDIUM',
    status: 'ACTIVE',
    category: 'WORK',
  },
];
